In [2]:
import torch

## 1. Different types of tensors 

In [3]:
# Creating a number 
t1 = torch.tensor(2.) # 2. is shorthand for 2.0 ## first tensor which is a floating point number 
print(t1, t1.dtype)
print(t1.shape)

tensor(2.) torch.float32
torch.Size([])


In [4]:
#Vector
t2 = torch.tensor( [ 1, 2, 3, 4])
print(t2, t2.dtype)
print(t2.shape)

tensor([1, 2, 3, 4]) torch.int64
torch.Size([4])


In [5]:
#matrix 
t3 = torch.tensor([[1.,2.],[3,4],[5.,6.]])
print(t3, t3.dtype)
print(t3.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) torch.float32
torch.Size([3, 2])


In [6]:
#tensor 
t4 = torch.tensor([[[1.,2.],[3,4],[5.,6.]]  , [[2.,3.],[4,5],[6.,7.]] ])
print(t4, t4.dtype)
print(t4.shape) # x matrices, each w/ y rows, z columns

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]],

        [[2., 3.],
         [4., 5.],
         [6., 7.]]]) torch.float32
torch.Size([2, 3, 2])


All matrices in a tensor should be of the same number of rows and columns. 

## 2.Tensor operations and gradients 

### requires_grad

In [7]:
x = torch.tensor(4.)
w = torch.tensor(3., requires_grad= True)
b = torch.tensor(5., requires_grad= True)


In [8]:
y = w * x + b  #normal linear reg operation on matrices
y

tensor(17., grad_fn=<AddBackward0>)

For tensors which requires_grad is set to True, when they are used to calculate a function, the function's derivative can be easily calculated w.r.t. them. 

In the example above, w and b have requires_grad set to True and are used to calculate y. 

--> dy/dw and dy/db can be easily calculated in that case. 

### .backward and .grad

In [9]:
#Compute derivatives 
y.backward()

The derivative of y w.r.t. to each tensor is stored in the respective tensor's '.grad' property. 

In [10]:
#Display derivatives using .grad 

print('dy/dx: {}'.format(x.grad))  # will be none because x's require_grad is False by default
print('dy/dw: {}'.format(w.grad)) #dy/dw equals x
print('dy/db: {}'.format(b.grad))

dy/dx: None
dy/dw: 4.0
dy/db: 1.0


## 3. Converting numpy array to pytorch tensor 
### torch.from_numpy(), .numpy() functions 

In [11]:
import numpy as np

In [12]:
x = np.array([[1, 2], [3, 4.]])
y = torch.from_numpy(x) ## converting numpy array to torch tensor


In [13]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [14]:
#Tensor to array
z  =  y.numpy()
z.dtype

dtype('float64')